apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pgdata
  namespace: quickpoll
spec:
  accessModes: ["ReadWriteOnce"]
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: db
  namespace: quickpoll
spec:
  replicas: 1
  selector:
    matchLabels: { app: db }
  strategy:
    type: Recreate
  template:
    metadata:
      labels: { app: db }
    spec:
      containers:
        - name: db
          image: postgres:16-alpine
          ports: [{ containerPort: 5432 }]
          envFrom:
            - secretRef: { name: quickpoll-secrets }
          volumeMounts:
            - name: pgdata
              mountPath: /var/lib/postgresql/data
      volumes:
        - name: pgdata
          persistentVolumeClaim: { claimName: pgdata }
---
apiVersion: v1
kind: Service
metadata:
  name: db
  namespace: quickpoll
spec:
  selector: { app: db }
  ports: [{ port: 5432, targetPort: 5432 }]
