apiVersion: apps/v1
kind: Deployment
metadata:
  name: worker
  namespace: quickpoll
spec:
  replicas: 1
  selector:
    matchLabels: { app: worker }
  template:
    metadata:
      labels: { app: worker }
    spec:
      containers:
        - name: worker
          image: quickpoll-worker:local
          imagePullPolicy: IfNotPresent
          envFrom:
            - secretRef: { name: quickpoll-secrets }
